# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6be33d6453d9835b0156b39d3a9c3895ec5bafce50f2a739a20c994bcc7c810f2dada680e671fde76eab1641e70edaa003c9496d6194d82dfcc76f38251f28d1
  locu_api_key: <%= ENV['LOCU_API_KEY'] %> # Rails.application.secrets.locu_api_key to use


test:
  secret_key_base: bcca6a0eb3f8230b89f55b7e30c4760a9012acafb3362b645438eb0912131d3d857f745b4dd22422b8b4fbc2eef224a61673d83f69d08aa66866f79835edad79
  locu_api_key: <%= ENV['LOCU_API_KEY'] %> # Rails.application.secrets.locu_api_key to use


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  locu_api_key: <%= ENV['LOCU_API_KEY'] %> # Rails.application.secrets.locu_api_key to use
